### ISSUE TITLE
MAIN CONTENT GOES HERE

### ISSUE THREAD

**Issue by nachoan** [satrun77/Global-Message-Moodle-Plugin#11]
Hello,

I added into /theme/essential/renderers/core_renderer.php the code for working with Global Message Plugin:

public function standard_end_of_body_html() {
global $CFG;
include_once $CFG->dirroot . '/local/globalmessage/lib/base.php';
moo_globalmessage::show_message();
return parent::standard_end_of_body_html();
}

I have upgraded Essential Theme version and when I'm going to edit the topic of a Moodle course I have an error message. The error disappears if I delete the above lines in core_renderer.php but then I cannot use your plugins.

URL example:
https://mymoodle.org/course/editsection.php?id=6099&sr=0

[MAIN CONTENT GOES HERE - W6wfqDSYxx]

Moodle version: 2.7.11 (2014051211.00)
Essential theme version: 2.7.9.5.2 (Build: 2014111010)
Global Message version: 2014110501

What can I do? I would appreciate your help.

**Comment by satrun77** [comment]
What is the version of PHP in your server?

**Comment by nachoan** [comment]
Hi,

My php version is PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31)

I have also upgraded Globalmessage plugin to 2015040100

**Comment by satrun77** [comment]
Version 2015040100 is for Moodle 2.8 and onward.
Version 2014110501 is for Moodle 2.7

I have installed 2014110501 with Moodle 2.7. I'm unable to replicate the issue. Can you please clear Moodle cache and true debugging on. Then try to replicate the issue. 

Turning debugging may show more information about the issue.

**Comment by nachoan** [comment]
I would like to thank you for your time and patience. I'm sorry to waste your time. We did an error in one of the extra rules. A college used a function which gave that error message.

About the version we want to upgrade to Moodle 2.9 soon however, I'm still using 2015040100 version under Moodle 2.7.11 and it's working. 

Thanks again!

**Comment by satrun77** [comment]
Thanks ok. It is good the plugin is working :)
