### ISSUE TITLE
New Release for 2.8?

### ISSUE THREAD

**Issue by btindell** [satrun77/Global-Message-Moodle-Plugin#5]
Hello,

There has been much talk on https://moodle.org/plugins/view/local_globalmessage about this plugin. Multiple people, myself included, have been trying to get this up and running for 2.8. I have yet to get the simple welcome message to work. On Feb 4th, you posted in that thread you were working on a fix? How close are you to releasing a new version? 

I have been working on fixing this myself since this plugin is vital to our setup, in order to post outages to our users. I have been running into an error "Unable to find file '/docs/lib/yuilib/2in3/2.9.0/build/assets/skins/sam/sprite.png'". This comes in your plugin when you create the "div class='hd' ". 

Furthermore, there is no longer a "renders.php" file for any of the themes for 2.8. How do you propose to incorporate the "standard_end_of_body_html()" function that we have to add to our theme?

Please let me know if I can help to get this plugin working for 2.8. 

Thanks,

Ben

**Comment by satrun77** [comment]
Hi Ben

Have you tried installing the plugin from this repository. It contains few changes to make it compatible with Moodle 2.8. These changes are not imported into Moodle site.

You can still use renders.php in Moodle 2.8. For example if you theme is based on clean or bootstrapbase, then your renders.php should look like:

```
<?php

require_once(__DIR__ . '/../bootstrapbase/renderers.php');

class theme_clean_core_renderer extends theme_bootstrapbase_core_renderer
{
    public function standard_end_of_body_html() {
        global $CFG;

        include_once $CFG->dirroot . '/local/globalmessage/lib/base.php';
        moo_globalmessage::show_message();

        return parent::standard_end_of_body_html();
    }
}
```

**Comment by btindell** [comment]
Thank you, I will update the plugin from the most recent commit in the repository.

We are using the clean theme, and from what Im seeing, based on what we got from moodle.org, there is no renders.php file. Based on what youre saying, since I dont have a renders.php file, I should create one like that?

**Comment by satrun77** [comment]
Yes create rendere.php same as the code above.

**Comment by btindell** [comment]
Hello, I have created the renderers.php and I have updated the plugin from this repository. It appears to me that the show_message() function is being called, however somewhere in that function, the actual message is not being rendered.

**Comment by satrun77** [comment]
Can you post more details about your setup? The message details, design, and rules.

**Comment by btindell** [comment]
I was using the "Welcome to our Moodle Instance" rules and this was not working. I changed the rules to display after a certain date and it works! There are a couple CSS issues however I can mend these out with the rest of my team. Thank you for all your help, it is much appreciated!

**Comment by satrun77** [comment]
Thats great everything is working. Are the CSS issue related to the pluing? if they are please let me know what they are or you are welcome to send pull request.

**Comment by btindell** [comment]
Yes they are related to the plugin. I will create a pull request once we fix them. Thanks.
