### ISSUE TITLE
Installation Instruction Update

### ISSUE THREAD

**Issue by btindell** [satrun77/Global-Message-Moodle-Plugin#7]
Hello, 

Following the instructions in the documentation for the installation, we ran into troubles. For some reason the call to "class theme_[theme name]_core_renderer extends theme_bootstrapbase_core_renderer" screwed up a lot of our CSS. We were able to do away with the renderers.php file and we decided to put the calls into the columns1.php, columns2.php, and columns3.php of the respective theme that we are using. 

We placed the calls to global message where the main content of the page was being rendered like so:
<section id="region-main" class="span12">
   <?php
      include_once $CFG->dirroot . '/local/globalmessage/lib/base.php';
      moo_globalmessage::show_message();
      echo $OUTPUT->course_content_header();
      echo $OUTPUT->main_content();
      echo $OUTPUT->course_content_footer();
   ?>
 </section>

This fixed our issue, and I thought I would share it just in case someone was running into the same trouble.

Thanks,

Ben Tindell

**Comment by satrun77** [comment]
Thanks for sharing this. I will add it to the read me file under Q/A section.
