### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by nachoan** [satrun77/Global-Message-Moodle-Plugin#8]
Hi,

I'm using Essential Theme () in Moodle 2.7.2
I have installed Global Message Local Pluging following instructions, step 5 is ok, but in step 6 I have lost myself, this is the renderes.php of this theme, where can I put the lines I need?
(I think step 7 and 8 are are 6.1 and 6.2 but there is 6.1 into the Installation text)
--------------------------------------------------------------------------
<?php
global $CFG;

require_once('renderers/core_renderer.php');
require_once('renderers/format_topics_renderer.php');
require_once('renderers/format_weeks_renderer.php');
require_once('renderers/format_topcoll_renderer.php');
require_once('renderers/format_grid_renderer.php');
require_once('renderers/format_noticebd_renderer.php');
require_once('renderers/format_columns_renderer.php');

if (theme_essential_get_setting('enablecategoryicon')) {
    require_once('renderers/core_course_renderer.php');
}

if (intval($CFG->version) >= 2013111800) {
    require_once('renderers/core_renderer_maintenance.php');
    require_once('renderers/core_course_management_renderer.php');
}

**Comment by satrun77** [comment]
The theme is separating the renderer classes into several files. 

You need to open the following file: https://github.com/gjb2048/moodle-theme_essential/blob/master/renderers/core_renderer.php#L1593
 
On line 1593 add the following code:

```
  public function standard_end_of_body_html() {
        global $CFG;

        include_once $CFG->dirroot . '/local/globalmessage/lib/base.php';
        moo_globalmessage::show_message();

        return parent::standard_end_of_body_html();
    }
```

**Comment by nachoan** [comment]
Thanks! It works.
